basePath: /
definitions:
  models.UserResponse:
    properties:
      id:
        example: "123"
        type: string
      name:
        example: John Doe
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger docs for POS system
  title: POS System API
  version: "1.0"
paths:
  /api/user/{id}:
    get:
      description: Retrieve user details using ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
      summary: Get user by ID
      tags:
      - Users
swagger: "2.0"
